version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BestFootForwardDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - your_network

  api:
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - postgres
    ports:
      - "8080:80"
    networks:
      - your_network
    volumes:
      - ./logs:/app/logs    
    command: ["tail", "-f", "/dev/null"]

networks:
  your_network:
    driver: bridge
